import { NextRequest, NextResponse } from "next/server";


const GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";


const QUESTION_SCHEMA = {
  type: "object",
  properties: {
    questions: {
      type: "array",
      description: "A list of 3 interview questions",
      items: {
        type: "object",
        properties: {
          question: { 
            type: "string",
            description: "The interview question text" 
          },
          rationale: { 
            type: "string",
            description: "Why this question is effective for evaluating the candidate" 
          }
        },
        required: ["question", "rationale"]
      }
    }
  },
  required: ["questions"]
};

// Prompt Builder
function buildPrompt(jobTitle: string): string {
  return `Act as an expert hiring manager and interviewer with 15+ years of experience.
Generate exactly 3 thoughtful, insightful interview questions for a "${jobTitle}" role.

Requirements:
- Be specific to the "${jobTitle}" role, not generic.
- Test for real skills, judgment, or mindset relevant to this role.
- Avoid yes/no questions — ask for examples or thinking processes.`;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { jobTitle } = body;

    // Validate Input: Basic security and user experience check
    if (!jobTitle || typeof jobTitle !== "string" || jobTitle.trim().length === 0) {
      return NextResponse.json(
        { message: "Job title is required" },
        { status: 400 }
      );
    }
    
    // Sanitize: Limit input length to prevent prompt injection or excessive token use
    const sanitizedTitle = jobTitle.trim().slice(0, 100);
    const apiKey = process.env.GEMINI_API_KEY;

    // API Key Check: Ensure the environment is correctly configured
    if (!apiKey) {
      return NextResponse.json(
        { message: "API key not configured on server" },
        { status: 500 }
      );
    }

    // The Gemini API Call
    const geminiResponse = await fetch(`${GEMINI_API_URL}?key=${apiKey}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: buildPrompt(sanitizedTitle)}],
          },
        ],
        generationConfig: {
          temperature: 0.7, // Balance between creative variety and consistency
          maxOutputTokens: 2000, // Ample room for 3 detailed questions and rationales
          response_mime_type: "application/json",
          response_schema: QUESTION_SCHEMA,
        },
      }),
    });

    // Advanced Error Handling
    if (!geminiResponse.ok) {
      const errorData = await geminiResponse.json();
      
      // Specifically handle the 429 Quota error you encountered
      if (geminiResponse.status === 429) {
        return NextResponse.json(
          { message: "AI Quota exceeded. Please wait 60 seconds and try again." },
          { status: 429 }
        );
      }

      console.error("Gemini API error:", errorData);
      return NextResponse.json(
        { message: "AI service error. Please try again later." },
        { status: 502 }
      );
    }

    const geminiData = await geminiResponse.json();
    
    // Extract the JSON text content
    const rawText = geminiData?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!rawText) {
      return NextResponse.json(
        { message: "No content generated by AI." },
        { status: 502 }
      );
    }
    
    const parsed = JSON.parse(rawText);
    
    return NextResponse.json(parsed);

  } catch (error) {
    console.error("Unexpected error in API route:", error);
    return NextResponse.json(
      { message: "An unexpected error occurred" },
      { status: 500 }
    );
  }
}